accessing
annotateError: anError
	self errors add: anError